#docker-compose up --build -d
#docker-compose down  
version: "3"

services:

  api:
    build: 
      context: "./"
      dockerfile: ./ShopAPI/ShopAPI/dockerfile
    networks:
      - internal-network


  identity:
    build:
      context: "./"
      dockerfile: IdentityServer/IdentityServer/dockerfile
    networks:
      - internal-network


  file:
    build:
      context: "./"
      dockerfile: FileServer/FileServer/dockerfile
    networks:
      - internal-network


  nginx:
    build:
      context: "./"
      dockerfile: nginx/dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - identity
      - file
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

