#docker-compose up --build -d
#docker-compose down  
version: "3"

services:

  api:
    build: 
      context: "./"
      dockerfile: ./ShopAPI/ShopAPI/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
      - ./appsettings.Production.json:/app/conf/ShopApi/appsettings.Production.json:ro
    networks:
      - internal-network


  identity:
    build:
      context: "./"
      dockerfile: IdentityServer/IdentityServer/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
      - ./appsettings.Production.json:/app/conf/IdentityServer/appsettings.Production.json:ro
    networks:
      - internal-network


  file:
    build:
      context: "./"
      dockerfile: FileServer/FileServer/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static 
      - ./appsettings.Production.json:/app/conf/FileServer/appsettings.Production.json:ro
    networks:
      - internal-network 


  nginx:
    build:
      context: "./"
      dockerfile: nginx/dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - identity
      - file
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

