# укажем, на основе какого образа будем 
# делать наш контейнер. Для сборки приложения используем dotnet-sdk 
# и назовём этот образ builder
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS builder 
# укажем директорию для нашего приложения внутри контейнера
WORKDIR /service

# Скопируем все файлы из проекта в файловую систему контейнера
COPY . ./
# Запустим restore для загрузки зависимостей
RUN dotnet restore --configfile ShopBackend.sln
# Опубликуем собранный dll в папку "output"
RUN dotnet publish /ShopAPI -c Release -o pub

# Теперь соберём образ, в котором наше приложение 
# будет запущено. Для запуска приложения достаточно
# среды выполнения aspnet, без sdk
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /service
# Скопируем файлы приложения из предыдущего образа 
COPY --from=builder /service/pub .
# укажем команду, которая будет запускать приложение
ENTRYPOINT ["dotnet", "ShopAPI.dll"]